/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "consumer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void *
_subscribe_1 (topics  *argp, struct svc_req *rqstp)
{
	return (subscribe_1_svc(*argp, rqstp));
}

static void *
_unsubscribe_1 (void  *argp, struct svc_req *rqstp)
{
	return (unsubscribe_1_svc(rqstp));
}

static topics *
_subscription_1 (void  *argp, struct svc_req *rqstp)
{
	return (subscription_1_svc(rqstp));
}

static partitionInfoList *
_partitionsfor_1 (char * *argp, struct svc_req *rqstp)
{
	return (partitionsfor_1_svc(*argp, rqstp));
}

static consumerRecordList *
_poll_1 (quad_t  *argp, struct svc_req *rqstp)
{
	return (poll_1_svc(*argp, rqstp));
}

static quad_t *
_position_1 (position_1_argument *argp, struct svc_req *rqstp)
{
	return (position_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void *
_seek_1 (seek_1_argument *argp, struct svc_req *rqstp)
{
	return (seek_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static void *
_seektobeginning_1 (seektobeginning_1_argument *argp, struct svc_req *rqstp)
{
	return (seektobeginning_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void *
_seektoend_1 (seektoend_1_argument *argp, struct svc_req *rqstp)
{
	return (seektoend_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void *
_close_1 (void  *argp, struct svc_req *rqstp)
{
	return (close_1_svc(rqstp));
}

static void
consumer_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		topics subscribe_1_arg;
		char *partitionsfor_1_arg;
		quad_t poll_1_arg;
		position_1_argument position_1_arg;
		seek_1_argument seek_1_arg;
		seektobeginning_1_argument seektobeginning_1_arg;
		seektoend_1_argument seektoend_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case subscribe:
		_xdr_argument = (xdrproc_t) xdr_topics;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _subscribe_1;
		break;

	case unsubscribe:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _unsubscribe_1;
		break;

	case subscription:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_topics;
		local = (char *(*)(char *, struct svc_req *)) _subscription_1;
		break;

	case partitionsFor:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_partitionInfoList;
		local = (char *(*)(char *, struct svc_req *)) _partitionsfor_1;
		break;

	case poll:
		_xdr_argument = (xdrproc_t) xdr_quad_t;
		_xdr_result = (xdrproc_t) xdr_consumerRecordList;
		local = (char *(*)(char *, struct svc_req *)) _poll_1;
		break;

	case position:
		_xdr_argument = (xdrproc_t) xdr_position_1_argument;
		_xdr_result = (xdrproc_t) xdr_quad_t;
		local = (char *(*)(char *, struct svc_req *)) _position_1;
		break;

	case seek:
		_xdr_argument = (xdrproc_t) xdr_seek_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _seek_1;
		break;

	case seekToBeginning:
		_xdr_argument = (xdrproc_t) xdr_seektobeginning_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _seektobeginning_1;
		break;

	case seekToEnd:
		_xdr_argument = (xdrproc_t) xdr_seektoend_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _seektoend_1;
		break;

	case close:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _close_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CONSUMER, CONSUMERVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CONSUMER, CONSUMERVERS, consumer_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CONSUMER, CONSUMERVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CONSUMER, CONSUMERVERS, consumer_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CONSUMER, CONSUMERVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
