/*
 * Automatically generated by jrpcgen 1.0.7 on 6/8/16 1:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class consumerRecordList implements XdrAble {

    public consumerRecord value;

    public consumerRecordList() {
    }

    public consumerRecordList(consumerRecord value) {
        this.value = value;
    }

    public consumerRecordList(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        if ( value != null ) { xdr.xdrEncodeBoolean(true); value.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeBoolean() ? new consumerRecord(xdr) : null;
    }

}
// End of consumerRecordList.java
