/*
 * Automatically generated by jrpcgen 1.0.7 on 6/9/16 3:09 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class partitionInfoList implements XdrAble {

    public partitionInfo value;

    public partitionInfoList() {
    }

    public partitionInfoList(partitionInfo value) {
        this.value = value;
    }

    public partitionInfoList(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        if ( value != null ) { xdr.xdrEncodeBoolean(true); value.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeBoolean() ? new partitionInfo(xdr) : null;
    }

}
// End of partitionInfoList.java
