/*
 * Automatically generated by jrpcgen 1.0.7 on 6/8/16 1:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "consumer" ONC/RPC program.
 */
public interface consumer {
    public static final int partitionsFor_1 = 5;
    public static final int position_1 = 7;
    public static final int subscribe_1 = 2;
    public static final int close_1 = 11;
    public static final int seekToEnd_1 = 10;
    public static final int poll_1 = 6;
    public static final int MAXTOPICNAMELEN = 20;
    public static final int MAXKEYLEN = 10;
    public static final int seekToBeginning_1 = 9;
    public static final int subscription_1 = 4;
    public static final int unsubscribe_1 = 3;
    public static final int CONSUMERVERS = 1;
    public static final int CONSUMER = 0x20000002;
    public static final int seek_1 = 8;
    public static final int connect_1 = 1;
}
// End of consumer.java
