/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRODUCER_H_RPCGEN
#define _PRODUCER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct call_result {
	int error;
	union {
		int errid;
	} call_result_u;
};
typedef struct call_result call_result;

struct send_1_argument {
	char *arg1;
	char *arg2;
	char *arg3;
};
typedef struct send_1_argument send_1_argument;

struct sendwithack_1_argument {
	char *arg1;
	char *arg2;
	char *arg3;
};
typedef struct sendwithack_1_argument sendwithack_1_argument;

#define PRODUCER 0x20000001
#define PRODUCERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define connect 1
extern  call_result * connect_1(CLIENT *);
extern  call_result * connect_1_svc(struct svc_req *);
#define send 2
extern  void * send_1(char *, char *, char *, CLIENT *);
extern  void * send_1_svc(char *, char *, char *, struct svc_req *);
#define sendWithAck 3
extern  call_result * sendwithack_1(char *, char *, char *, CLIENT *);
extern  call_result * sendwithack_1_svc(char *, char *, char *, struct svc_req *);
#define flush 4
extern  void * flush_1(CLIENT *);
extern  void * flush_1_svc(struct svc_req *);
#define close 5
extern  void * close_1(CLIENT *);
extern  void * close_1_svc(struct svc_req *);
#define closeAfter 6
extern  void * closeafter_1(quad_t , CLIENT *);
extern  void * closeafter_1_svc(quad_t , struct svc_req *);
extern int producer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define connect 1
extern  call_result * connect_1();
extern  call_result * connect_1_svc();
#define send 2
extern  void * send_1();
extern  void * send_1_svc();
#define sendWithAck 3
extern  call_result * sendwithack_1();
extern  call_result * sendwithack_1_svc();
#define flush 4
extern  void * flush_1();
extern  void * flush_1_svc();
#define close 5
extern  void * close_1();
extern  void * close_1_svc();
#define closeAfter 6
extern  void * closeafter_1();
extern  void * closeafter_1_svc();
extern int producer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_call_result (XDR *, call_result*);
extern  bool_t xdr_send_1_argument (XDR *, send_1_argument*);
extern  bool_t xdr_sendwithack_1_argument (XDR *, sendwithack_1_argument*);

#else /* K&R C */
extern bool_t xdr_call_result ();
extern bool_t xdr_send_1_argument ();
extern bool_t xdr_sendwithack_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRODUCER_H_RPCGEN */
