/*
 * Automatically generated by jrpcgen 1.0.7 on 5/20/16 3:20 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class producerServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public producerServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public producerServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public producerServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(producer.PRODUCER, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 1: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                call_result result$ = connect_1();
                call.reply(result$);
                break;
            }
            case 2: {
                class XdrAble$ implements XdrAble {
                    public String arg1;
                    public String arg2;
                    public int arg3;
                    public void xdrEncode(XdrEncodingStream xdr)
                        throws OncRpcException, IOException {
                    }
                    public void xdrDecode(XdrDecodingStream xdr)
                        throws OncRpcException, IOException {
                        arg1 = xdr.xdrDecodeString();
                        arg2 = xdr.xdrDecodeString();
                        arg3 = xdr.xdrDecodeInt();
                    }
                };
                XdrAble$ args$ = new XdrAble$();
                call.retrieveCall(args$);
                send_1(args$.arg1, args$.arg2, args$.arg3);
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 3: {
                class XdrAble$ implements XdrAble {
                    public String arg1;
                    public String arg2;
                    public int arg3;
                    public void xdrEncode(XdrEncodingStream xdr)
                        throws OncRpcException, IOException {
                    }
                    public void xdrDecode(XdrDecodingStream xdr)
                        throws OncRpcException, IOException {
                        arg1 = xdr.xdrDecodeString();
                        arg2 = xdr.xdrDecodeString();
                        arg3 = xdr.xdrDecodeInt();
                    }
                };
                XdrAble$ args$ = new XdrAble$();
                call.retrieveCall(args$);
                call_result result$ = sendWithAck_1(args$.arg1, args$.arg2, args$.arg3);
                call.reply(result$);
                break;
            }
            case 4: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                flush_1();
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 5: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                close_1();
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 6: {
                XdrLong args$ = new XdrLong();
                call.retrieveCall(args$);
                closeLater_1(args$.longValue());
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract call_result connect_1();

    public abstract void send_1(String arg1, String arg2, int arg3);

    public abstract call_result sendWithAck_1(String arg1, String arg2, int arg3);

    public abstract void flush_1();

    public abstract void close_1();

    public abstract void closeLater_1(long arg1);

}
// End of producerServerStub.java
