/*
 * Automatically generated by jrpcgen 1.0.7 on 6/3/16 5:56 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "producer" ONC/RPC program.
 */
public interface producer {
    public static final int PRODUCER = 0x20000001;
    public static final int closeAfter_1 = 6;
    public static final int send_1 = 2;
    public static final int flush_1 = 4;
    public static final int connect_1 = 1;
    public static final int PRODUCERVERS = 1;
    public static final int sendWithAck_1 = 3;
    public static final int close_1 = 5;
}
// End of producer.java
