/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "producer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static call_result *
_connect_1 (void  *argp, struct svc_req *rqstp)
{
	return (connect_1_svc(rqstp));
}

static void *
_send_1 (send_1_argument *argp, struct svc_req *rqstp)
{
	return (send_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static call_result *
_sendwithack_1 (sendwithack_1_argument *argp, struct svc_req *rqstp)
{
	return (sendwithack_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static void *
_flush_1 (void  *argp, struct svc_req *rqstp)
{
	return (flush_1_svc(rqstp));
}

static void *
_close_1 (void  *argp, struct svc_req *rqstp)
{
	return (close_1_svc(rqstp));
}

static void *
_closelater_1 (quad_t  *argp, struct svc_req *rqstp)
{
	return (closelater_1_svc(*argp, rqstp));
}

static void
producer_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		send_1_argument send_1_arg;
		sendwithack_1_argument sendwithack_1_arg;
		quad_t closelater_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case connect:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_call_result;
		local = (char *(*)(char *, struct svc_req *)) _connect_1;
		break;

	case send:
		_xdr_argument = (xdrproc_t) xdr_send_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _send_1;
		break;

	case sendWithAck:
		_xdr_argument = (xdrproc_t) xdr_sendwithack_1_argument;
		_xdr_result = (xdrproc_t) xdr_call_result;
		local = (char *(*)(char *, struct svc_req *)) _sendwithack_1;
		break;

	case flush:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _flush_1;
		break;

	case close:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _close_1;
		break;

	case closeLater:
		_xdr_argument = (xdrproc_t) xdr_quad_t;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _closelater_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PRODUCER, PRODUCERVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PRODUCER, PRODUCERVERS, producer_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PRODUCER, PRODUCERVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PRODUCER, PRODUCERVERS, producer_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PRODUCER, PRODUCERVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
